/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_882654_16.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_882654_1[] = { "0", "1", "2" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_882654_15_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };
const uint32_t ei_dsp_config_882654_15_axes_size = 15;
ei_dsp_config_flatten_t ei_dsp_config_882654_15 = {
    15, // uint32_t blockId
    1, // int implementationVersion
    15, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const float ei_dn_standard_scaler_mean_882654_15[105] = { 5.758491978049278, -3.9382666674527256, 18.13018041307276, 10.288675806739114, 8.080280948768962, 0.0411941066109152, -1.6895480000159957, 43.10700780695135, 0, 89.13636363636364, 58.82595391706987, 40.022090218283914, -0.12384954111819918, -1.9306013909253208, 5.065970372069966, 0, 11.432000962170688, 6.97516964782368, 4.792898394844749, -0.04210073633161797, -1.8124403459104625, 45.90359809181907, 0, 96.53636342828923, 62.70435636693781, 42.7097205248746, -0.11042769693515518, -1.9140828197652644, 0.07336323061793916, -0.768075745341114, 0.9353959696706046, 0.48037544430487533, 0.4455536355857145, -0.31516433698760177, 0.7598793096840382, 0.06355652461272919, -0.11913346281190487, 0.27385796331377193, 0.14804437434808773, 0.12019975851713256, -0.34415827657688747, 1.1170401473698968, 5.071900654922832, 0, 11.687449910423972, 6.985157208009199, 4.801302768967369, -0.03522033245429735, -1.7998014641079036, 5.094903154806658, 0, 11.674133430827748, 7.0145073695616285, 4.81964062018828, -0.03971250994469632, -1.806039772927761, 0.18148213215383954, 0, 0.6089861487800424, 0.2889722951433875, 0.2201971078968861, 1.4989614305192267, 1.7369580303572796, 0.047183796848085796, 0, 0.26883617966351187, 0.08483079528774727, 0.07001530793918805, 1.7512873050502755, 3.6468369732187553, 49.49242609569972, 0, 91.45454545454545, 67.27421326461163, 45.56315916641192, 0.08909425241026012, -2.240138179199262, 0.17613636490634896, 0, 0.5454545454545454, 0.30366482585668564, 0.24516095559705386, 0.507729285819964, -1.4977691451256925, 2.886529236439277, 0, 7.844596322117881, 4.193193502893502, 3.022734303112057, 0.8210725269111042, -0.4175969927825711, 0.02282197023106908, 0, 0.29318182255056774, 0.07407657158645717, 0.07006382057443261, 2.7923819449814884, 8.849307690239089, 0.029924243201755664, 0, 0.25227272510528564, 0.07339821463789452, 0.06646218527616425, 2.124564476311207, 3.9694336493584244 };
const float ei_dn_standard_scaler_scale_882654_15[105] = { 0.3803458081615363, 0.10086834358504979, 0.060473768516187645, 0.1282072893084909, 0.12769090344284661, 3.2808832965677905, 1.9335763546567724, 0.43392092577207775, 1, 0.13833742262067436, 0.34241497114257846, 0.5178537550211963, 17.226259094513356, 32.838025929095, 0.5779070955669836, 1, 0.19926195580434533, 0.40867649934778066, 0.5763643372409989, 5.379622649562897, 2.7961987560758983, 0.3760855239114312, 1, 0.13536335976840586, 0.29250964036898613, 0.4388253827785972, 17.035829816276834, 29.57871077332128, 4.845288753911898, 0.6978889735120704, 0.6873264039927606, 1.4231237605530107, 1.4463562043807392, 0.7401188752872484, 0.20749825039009082, 8.776884775574063, 7.289498592213448, 3.437907914699468, 6.969789795293206, 9.519987415366723, 0.8022994298477885, 0.27631358688414015, 0.5753270471352931, 1, 0.20247151776315633, 0.40710369643523164, 0.5746381765334404, 5.59654959887555, 2.9052047446535205, 0.581626838357078, 1, 0.20370745076806915, 0.4113950007524023, 0.5803702937287109, 5.51668862865759, 2.833124676182583, 2.753021178224064, 1, 1.1169011707910923, 1.9607134623084108, 2.7707326884738412, 0.8745503962148206, 0.22716290178647933, 29.427174019653904, 1, 5.359175254494032, 15.910104799551918, 18.68738834114295, 0.9492278035292516, 0.21922519375263583, 0.0064251112171373435, 1, 0.003480589182561791, 0.00472894602529883, 0.006985397923113522, 2.9416801883716506, 1.4367823834810927, 5.560359671624587, 1, 2.0083160441856083, 3.4518890083853737, 4.357540059304173, 1.1960942532105767, 0.2921824157039491, 0.15670113077724995, 1, 0.05929670583341418, 0.10936680806911468, 0.15250964388305477, 1.880226156063384, 0.6958939011418479, 38.39746082517452, 1, 5.167181542374858, 17.043452455074757, 18.824799503194228, 0.5738505768158194, 0.11686335714381679, 38.74192706984383, 1, 2.9814925410648927, 14.345985351388988, 15.308213044950154, 1.0009711434634376, 0.18008478801824596 };
const float ei_dn_standard_scaler_var_882654_15[105] = { 6.912620764894345, 98.28567436118797, 273.4424481350067, 60.83794894001506, 61.331004896472926, 0.09290058205844276, 0.2674713975691056, 5.311030691759088, 0, 52.25413223140497, 8.5289292244439, 3.72894296314207, 0.00336990804175156, 0.0009273547848018339, 2.994221651289874, 0, 25.185537427255838, 5.98743305630154, 3.01027241092267, 0.03455384439590814, 0.12789805017668468, 7.070119686090879, 0, 54.57550331809395, 11.687446401703598, 5.1929784379638155, 0.0034456678772919786, 0.001142987598874324, 0.042595201035773717, 2.05318142583496, 2.1167713277982796, 0.4937585858748747, 0.47802374963654604, 1.8255639021934202, 23.225823519773755, 0.012981330474722858, 0.018819352940942172, 0.08460801777608663, 0.02058546300537353, 0.011033854466445727, 1.5535564301862836, 13.097714479107822, 3.0211369815811833, 0, 24.393387969001072, 6.033786077089388, 3.0283847419297554, 0.031927086286640025, 0.1184803996583002, 2.9560455614963264, 0, 24.098286985028427, 5.908564492593078, 2.96885953281959, 0.032858146026298045, 0.12458582329482076, 0.13194134148897418, 0, 0.8016236243194725, 0.26011879804152677, 0.130259900803031, 1.3074657415973112, 19.37872431963729, 0.0011547896559252332, 0, 0.03481802085317368, 0.003950516857204536, 0.002863536864867701, 1.1098367435453111, 20.807460307269693, 24223.60080009254, 0, 82545.70247933878, 44716.8585326665, 20493.57372850149, 0.11556041392227931, 0.4844154778941054, 0.03234403739036367, 0, 0.24793388429752092, 0.08392403456540644, 0.05266441002805655, 0.698987150986271, 11.713639369352173, 40.72449796242965, 0, 284.4060728164188, 83.60435980649734, 42.9937558652631, 0.28286539493251167, 2.064970916536912, 0.0006782580985563628, 0, 0.037453513038768024, 0.0034425864349349857, 0.002821884806658861, 3.036703254990198, 73.22228603880916, 0.0006662505207794188, 0, 0.11249482530577143, 0.004858914241051285, 0.004267278667172337, 0.9980605387728286, 30.835141238871902 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_882654_15 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_882654_15,
    .mean_data_len = 105,
    .scale_data = (float *)ei_dn_standard_scaler_scale_882654_15,
    .scale_data_len = 105,
    .var_data = (float *)ei_dn_standard_scaler_var_882654_15,
    .var_data_len = 105
};
ei_data_normalization_t ei_data_normalization_config_882654_15 = {
    (void *) &ei_data_normalization_standard_scaler_config_882654_15, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_882654_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_882654_1[ei_dsp_blocks_882654_1_size] = {
    { // DSP block 15
        15,
        105, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_882654_15, // pointer to config struct
        ei_dsp_config_882654_15_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_882654_15_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_882654_15, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_882654_16 = {
    .implementation_version = 1,
    .model = tflite_learn_882654_16,
    .model_size = tflite_learn_882654_16_len,
    .arena_size = tflite_learn_882654_16_arena_size
};

const uint8_t ei_output_tensors_indices_882654_16[1] = { 0 };
const uint8_t ei_output_tensors_size_882654_16 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_882654_16 = {
    .implementation_version = 1,
    .block_id = 16,
    .output_tensors_indices = ei_output_tensors_indices_882654_16,
    .output_tensors_size = ei_output_tensors_size_882654_16,
    .quantized = 1,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_882654_16,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_882654_1_size = 1;
const uint32_t ei_learning_block_882654_16_inputs[1] = { 15 };
const uint8_t ei_learning_block_882654_16_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_882654_1[ei_learning_blocks_882654_1_size] = {
    {
        16,
        &run_nn_inference,
        (void*)&ei_learning_block_config_882654_16,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_882654_16_inputs,
        ei_learning_block_882654_16_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_882654_16 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_882654_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_882654_1[ei_postprocessing_blocks_882654_1_size] = {
    {
        .block_id = 16,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_882654_16,
        .input_block_id = 16
    },
};

const uint8_t freeform_outputs_882654_1_size = 0;

uint32_t *freeform_outputs_882654_1 = nullptr;

const ei_impulse_t impulse_882654_1 = {
    .project_id = 882654,
    .project_owner = "banditkmnggsn",
    .project_name = "Cold-Room-Monitoring-Stephen-Chuang",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 3,

    .nn_input_frame_size = 105,
    .raw_sample_count = 24,
    .raw_samples_per_frame = 15,
    .dsp_input_frame_size = 24 * 15,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 5000,
    .frequency = 0.2,

    .dsp_blocks_size = ei_dsp_blocks_882654_1_size,
    .dsp_blocks = ei_dsp_blocks_882654_1,

    .learning_blocks_size = ei_learning_blocks_882654_1_size,
    .learning_blocks = ei_learning_blocks_882654_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_882654_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_882654_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "temperature1_c + humidity1_percent + temperature2_c + humidity2_percent + dT1 + dT2 + avgT1_5 + avgT2_5 + stdT1_5 + stdT2_5 + stuck_count1 + stuck_count2 + diffT + abs_dT1 + abs_dT2",
    .slice_size = (24/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_882654_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_882654_1_size,
    .freeform_outputs = freeform_outputs_882654_1
};

ei_impulse_handle_t impulse_handle_882654_1 = ei_impulse_handle_t( &impulse_882654_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_882654_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_882654_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_882654_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_882654_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
